// <auto-generated />
using System;
using Ef_Product1Management;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFProductCRUD.Migrations
{
    [DbContext(typeof(Product1Context))]
    partial class Product1ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Ef_Product1Management.Product", b =>
                {
                    b.Property<int>("PID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("productname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("productprice")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("productquantity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PID");

                    b.ToTable("Productdetails1");
                });
#pragma warning restore 612, 618
        }
    }
}
